# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

name = "mayu"
version = "0.1.15"
gleam = ">= 1.2.0"
description = "Moe-Counter Compatible Website Hit Counter"
licenses = ["GPL-3.0-only"]
repository = { type = "github", user = "Fuwn", repo = "mayu" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
gsv = ">= 1.4.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
mist = ">= 1.0.0 and < 2.0.0"
sqlight = ">= 0.9.0 and < 1.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
birl = ">= 1.6.1 and < 2.0.0"
envoy = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
